packageExtensions:
  "html-to-pdf@*":
    dependencies:
      # those below are needed for "@sentry/node" but it did not work specifying it for sentry
      # so it's configured for main package for now
      tslib: "*"
      cookie: "*"
  debug@*:
    dependencies:
      supports-color: "*"
  ws@*:
    dependencies:
      bufferutil: "*"
      utf-8-validate: "*"

yarnPath: .yarn/releases/yarn-3.0.0-rc.2.cjs
