---
version: "3.8"
services:
  printer-test:
    image: louisqode/html-to-pdf-test
    build:
      context: ../
      dockerfile: deploy/Dockerfile
      target: test
    container_name: html-to-pdf-test
    command: yarn test
    environment:
      - ENV=local
      - RELEASE_ID=edge

